# -*- coding: utf-8 -*-
"""Personal Expense Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnQUFHFRH9BsbnrGtYJfmEaWz8Z35dzX
"""

import json
import os
import matplotlib.pyplot as plt
from datetime import datetime

FILE_NAME = "expenses.json"

# Load existing data
def load_expenses():
    if os.path.exists(FILE_NAME):
        with open(FILE_NAME, "r") as file:
            return json.load(file)
    return []

# Save data
def save_expenses(expenses):
    with open(FILE_NAME, "w") as file:
        json.dump(expenses, file, indent=4)

# Add expense
def add_expense(expenses):
    try:
        amount = float(input("Enter amount: "))
    except ValueError:
        print("Invalid amount.\n")
        return

    category = input("Enter category (food, travel, etc.): ")
    note = input("Enter note: ")

    date_input = input("Enter date (YYYY-MM-DD) or press Enter for today: ")

    if date_input == "":
        date = datetime.today().strftime("%Y-%m-%d")
    else:
        try:
            datetime.strptime(date_input, "%Y-%m-%d")
            date = date_input
        except ValueError:
            print("Invalid date format.\n")
            return

    expense = {
        "amount": amount,
        "category": category,
        "note": note,
        "date": date
    }

    expenses.append(expense)
    save_expenses(expenses)
    print("Expense added successfully.\n")

# View all expenses
def view_expenses(expenses):
    if not expenses:
        print("No expenses found.\n")
        return

    for i, exp in enumerate(expenses, start=1):
        print(f"{i}. ₹{exp['amount']} | {exp['category']} | {exp['note']} | {exp['date']}")
    print()

# Total spending
def total_spending(expenses):
    total = sum(exp["amount"] for exp in expenses)
    print(f"Total Spending: ₹{total}\n")

# Category-wise summary
def category_summary(expenses):
    summary = {}

    for exp in expenses:
        cat = exp["category"]
        summary[cat] = summary.get(cat, 0) + exp["amount"]

    print("Category-wise Spending:")
    for cat, amt in summary.items():
        print(f"{cat}: ₹{amt}")
    print()

# Plot graph
def plot_expenses(expenses):
    if not expenses:
        print("No data to plot.\n")
        return

    summary = {}

    for exp in expenses:
        cat = exp["category"]
        summary[cat] = summary.get(cat, 0) + exp["amount"]

    categories = list(summary.keys())
    amounts = list(summary.values())

    plt.bar(categories, amounts)
    plt.xlabel("Categories")
    plt.ylabel("Amount (₹)")
    plt.title("Expense Distribution")

    plt.show()

# Filter by date
def filter_by_date(expenses):
    date = input("Enter date (YYYY-MM-DD): ")

    found = False
    for exp in expenses:
        if exp["date"] == date:
            print(f"₹{exp['amount']} | {exp['category']} | {exp['note']}")
            found = True

    if not found:
        print("No expenses found for this date.\n")
    else:
        print()

# Clear all expenses
def clear_expenses(expenses):
    confirm = input("Are you sure you want to delete ALL expenses? (yes/no): ").lower()

    if confirm == "yes":
        expenses.clear()
        save_expenses(expenses)
        print("All expenses have been deleted.\n")
    else:
        print("Operation cancelled.\n")

# Main menu
def main():
    expenses = load_expenses()

    while True:
        print("==== Expense Tracker ====")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Total Spending")
        print("4. Category Summary")
        print("5. Show Graph")
        print("6. Filter by Date")
        print("7. Clear All Expenses")
        print("8. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_expense(expenses)
        elif choice == "2":
            view_expenses(expenses)
        elif choice == "3":
            total_spending(expenses)
        elif choice == "4":
            category_summary(expenses)
        elif choice == "5":
            plot_expenses(expenses)
        elif choice == "6":
            filter_by_date(expenses)
        elif choice == "7":
            clear_expenses(expenses)
        elif choice == "8":
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Try again.\n")

if __name__ == "__main__":
    main()