{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOaWMH9FibIl/3EJAsCoFRW",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/basaaria123/Personal-Expense-Tracker/blob/main/Personal_Expense_Tracker.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "n2ykJfBb2zbg",
        "outputId": "1350eff9-9a7c-41e5-c964-b2a86b729f7f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "==== Expense Tracker ====\n",
            "1. Add Expense\n",
            "2. View Expenses\n",
            "3. Total Spending\n",
            "4. Category Summary\n",
            "5. Show Graph\n",
            "6. Filter by Date\n",
            "7. Clear All Expenses\n",
            "8. Exit\n"
          ]
        }
      ],
      "source": [
        "import json\n",
        "import os\n",
        "import matplotlib.pyplot as plt\n",
        "from datetime import datetime\n",
        "\n",
        "FILE_NAME = \"expenses.json\"\n",
        "\n",
        "# Load existing data\n",
        "def load_expenses():\n",
        "    if os.path.exists(FILE_NAME):\n",
        "        with open(FILE_NAME, \"r\") as file:\n",
        "            return json.load(file)\n",
        "    return []\n",
        "\n",
        "# Save data\n",
        "def save_expenses(expenses):\n",
        "    with open(FILE_NAME, \"w\") as file:\n",
        "        json.dump(expenses, file, indent=4)\n",
        "\n",
        "# Add expense\n",
        "def add_expense(expenses):\n",
        "    try:\n",
        "        amount = float(input(\"Enter amount: \"))\n",
        "    except ValueError:\n",
        "        print(\"Invalid amount.\\n\")\n",
        "        return\n",
        "\n",
        "    category = input(\"Enter category (food, travel, etc.): \")\n",
        "    note = input(\"Enter note: \")\n",
        "\n",
        "    date_input = input(\"Enter date (YYYY-MM-DD) or press Enter for today: \")\n",
        "\n",
        "    if date_input == \"\":\n",
        "        date = datetime.today().strftime(\"%Y-%m-%d\")\n",
        "    else:\n",
        "        try:\n",
        "            datetime.strptime(date_input, \"%Y-%m-%d\")\n",
        "            date = date_input\n",
        "        except ValueError:\n",
        "            print(\"Invalid date format.\\n\")\n",
        "            return\n",
        "\n",
        "    expense = {\n",
        "        \"amount\": amount,\n",
        "        \"category\": category,\n",
        "        \"note\": note,\n",
        "        \"date\": date\n",
        "    }\n",
        "\n",
        "    expenses.append(expense)\n",
        "    save_expenses(expenses)\n",
        "    print(\"Expense added successfully.\\n\")\n",
        "\n",
        "# View all expenses\n",
        "def view_expenses(expenses):\n",
        "    if not expenses:\n",
        "        print(\"No expenses found.\\n\")\n",
        "        return\n",
        "\n",
        "    for i, exp in enumerate(expenses, start=1):\n",
        "        print(f\"{i}. ₹{exp['amount']} | {exp['category']} | {exp['note']} | {exp['date']}\")\n",
        "    print()\n",
        "\n",
        "# Total spending\n",
        "def total_spending(expenses):\n",
        "    total = sum(exp[\"amount\"] for exp in expenses)\n",
        "    print(f\"Total Spending: ₹{total}\\n\")\n",
        "\n",
        "# Category-wise summary\n",
        "def category_summary(expenses):\n",
        "    summary = {}\n",
        "\n",
        "    for exp in expenses:\n",
        "        cat = exp[\"category\"]\n",
        "        summary[cat] = summary.get(cat, 0) + exp[\"amount\"]\n",
        "\n",
        "    print(\"Category-wise Spending:\")\n",
        "    for cat, amt in summary.items():\n",
        "        print(f\"{cat}: ₹{amt}\")\n",
        "    print()\n",
        "\n",
        "# Plot graph\n",
        "def plot_expenses(expenses):\n",
        "    if not expenses:\n",
        "        print(\"No data to plot.\\n\")\n",
        "        return\n",
        "\n",
        "    summary = {}\n",
        "\n",
        "    for exp in expenses:\n",
        "        cat = exp[\"category\"]\n",
        "        summary[cat] = summary.get(cat, 0) + exp[\"amount\"]\n",
        "\n",
        "    categories = list(summary.keys())\n",
        "    amounts = list(summary.values())\n",
        "\n",
        "    plt.bar(categories, amounts)\n",
        "    plt.xlabel(\"Categories\")\n",
        "    plt.ylabel(\"Amount (₹)\")\n",
        "    plt.title(\"Expense Distribution\")\n",
        "\n",
        "    plt.show()\n",
        "\n",
        "# Filter by date\n",
        "def filter_by_date(expenses):\n",
        "    date = input(\"Enter date (YYYY-MM-DD): \")\n",
        "\n",
        "    found = False\n",
        "    for exp in expenses:\n",
        "        if exp[\"date\"] == date:\n",
        "            print(f\"₹{exp['amount']} | {exp['category']} | {exp['note']}\")\n",
        "            found = True\n",
        "\n",
        "    if not found:\n",
        "        print(\"No expenses found for this date.\\n\")\n",
        "    else:\n",
        "        print()\n",
        "\n",
        "# Clear all expenses\n",
        "def clear_expenses(expenses):\n",
        "    confirm = input(\"Are you sure you want to delete ALL expenses? (yes/no): \").lower()\n",
        "\n",
        "    if confirm == \"yes\":\n",
        "        expenses.clear()\n",
        "        save_expenses(expenses)\n",
        "        print(\"All expenses have been deleted.\\n\")\n",
        "    else:\n",
        "        print(\"Operation cancelled.\\n\")\n",
        "\n",
        "# Main menu\n",
        "def main():\n",
        "    expenses = load_expenses()\n",
        "\n",
        "    while True:\n",
        "        print(\"==== Expense Tracker ====\")\n",
        "        print(\"1. Add Expense\")\n",
        "        print(\"2. View Expenses\")\n",
        "        print(\"3. Total Spending\")\n",
        "        print(\"4. Category Summary\")\n",
        "        print(\"5. Show Graph\")\n",
        "        print(\"6. Filter by Date\")\n",
        "        print(\"7. Clear All Expenses\")\n",
        "        print(\"8. Exit\")\n",
        "\n",
        "        choice = input(\"Enter choice: \")\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_expense(expenses)\n",
        "        elif choice == \"2\":\n",
        "            view_expenses(expenses)\n",
        "        elif choice == \"3\":\n",
        "            total_spending(expenses)\n",
        "        elif choice == \"4\":\n",
        "            category_summary(expenses)\n",
        "        elif choice == \"5\":\n",
        "            plot_expenses(expenses)\n",
        "        elif choice == \"6\":\n",
        "            filter_by_date(expenses)\n",
        "        elif choice == \"7\":\n",
        "            clear_expenses(expenses)\n",
        "        elif choice == \"8\":\n",
        "            print(\"Goodbye!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid choice. Try again.\\n\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}